AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 116

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: 'extend_self'
